name = "Enigmistics"
uuid = "60f105a3-a574-40c2-bc2c-c04e07a3e561"
authors = ["federico.mor "]
version = "0.1.0"

[deps]
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"

[compat]
ProgressMeter = "1.11.0"
